In [4]:
import pandas as pd

In [5]:
import requests 

docs_url = 'https://github.com/alexeygrigorev/llm-rag-workshop/raw/main/notebooks/documents.json'
docs_response = requests.get(docs_url)
documents_raw = docs_response.json()

documents = []

for course in documents_raw:
    course_name = course['course']

    for doc in course['documents']:
        doc['course'] = course_name
        documents.append(doc)

In [6]:
documents[1]

{'text': 'GitHub - DataTalksClub data-engineering-zoomcamp#prerequisites',
 'section': 'General course-related questions',
 'question': 'Course - What are the prerequisites for this course?',
 'course': 'data-engineering-zoomcamp'}

In [7]:
df = pd.DataFrame(documents,columns=['course','section', 'question', 'text'])

In [8]:
df.head()

course                           section  \
0  data-engineering-zoomcamp  General course-related questions   
1  data-engineering-zoomcamp  General course-related questions   
2  data-engineering-zoomcamp  General course-related questions   
3  data-engineering-zoomcamp  General course-related questions   
4  data-engineering-zoomcamp  General course-related questions   

                                            question  \
0               Course - When will the course start?   
1  Course - What are the prerequisites for this c...   
2  Course - Can I still join the course after the...   
3  Course - I have registered for the Data Engine...   
4   Course - What can I do before the course starts?   

                                                text  
0  The purpose of this document is to capture fre...  
1  GitHub - DataTalksClub data-engineering-zoomca...  
2  Yes, even if you don't register, you're still ...  
3  You don't need it. You're accepted. You can al...  
4  You can start by installing and setting up all...

In [9]:
# df.course == 'data-engineering-zoomcamp'
df[df.course == 'data-engineering-zoomcamp'] #limiting bot to only answer for data-engineering

course                           section  \
0    data-engineering-zoomcamp  General course-related questions   
1    data-engineering-zoomcamp  General course-related questions   
2    data-engineering-zoomcamp  General course-related questions   
3    data-engineering-zoomcamp  General course-related questions   
4    data-engineering-zoomcamp  General course-related questions   
..                         ...                               ...   
430  data-engineering-zoomcamp           Workshop 2 - RisingWave   
431  data-engineering-zoomcamp           Workshop 2 - RisingWave   
432  data-engineering-zoomcamp           Workshop 2 - RisingWave   
433  data-engineering-zoomcamp          Triggers in Mage via CLI   
434  data-engineering-zoomcamp          Triggers in Mage via CLI   

                                              question  \
0                 Course - When will the course start?   
1    Course - What are the prerequisites for this c...   
2    Course - Can I still join the course after the...   
3    Course - I have registered for the Data Engine...   
4     Course - What can I do before the course starts?   
..                                                 ...   
430  Unable to Open Dashboard as xdg-open doesn’t o...   
431  Resolving Python Interpreter Path Inconsistenc...   
432                    How does windowing work in Sql?   
433  Encountering the error "ModuleNotFoundError: N...   
434                                     Basic Commands   

                                                  text  
0    The purpose of this document is to capture fre...  
1    GitHub - DataTalksClub data-engineering-zoomca...  
2    Yes, even if you don't register, you're still ...  
3    You don't need it. You're accepted. You can al...  
4    You can start by installing and setting up all...  
..                                                 ...  
430  Refer to the solution given in the first solut...  
431  Example Error:\nWhen attempting to execute a P...  
432  Ans : Windowing in streaming SQL involves defi...  
433  Python 3.12.1, is not compatible with kafka-py...  
434  Docker Commands\n# Create a Docker Image from ...  

[435 rows x 4 columns]

Vector spaces

--turn the docs in vectors
-- term document matrix:
    - ros: documents
    - columns : words/token
- bag of words:
    we dont care about the order of word on this ,order is lost
    - sparse matrix representataion

In [10]:
from sklearn.feature_extraction.text import CountVectorizer

In [11]:
cv=CountVectorizer(min_df=5)

In [12]:
cv.fit(df.text)

CountVectorizer(min_df=5)

In [13]:
cv.get_feature_names_out()

array(['01', '02', '03', ..., 'youtube', 'zip', 'zoomcamp'], dtype=object)

In [14]:
docs_example = [
    "Course starts on 15th Jan 2024",
    "Prerequisites listed on GitHub",
    "Submit homeworks after start date",
    "Registration not required for participation",
    "Setup Google Cloud and Python before course"
]

In [15]:
cv =CountVectorizer(stop_words='english')
cv.fit(docs_example)

CountVectorizer(stop_words='english')

In [16]:
cv.get_feature_names_out()

array(['15th', '2024', 'cloud', 'course', 'date', 'github', 'google',
       'homeworks', 'jan', 'listed', 'participation', 'prerequisites',
       'python', 'registration', 'required', 'setup', 'start', 'starts',
       'submit'], dtype=object)

In [17]:
X = cv.transform(docs_example)

In [18]:
X.todense()

matrix([[1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
        [0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0],
        [0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0]])

In [19]:
pd.DataFrame(X.todense(),columns=cv.get_feature_names_out()).T

0  1  2  3  4
15th           1  0  0  0  0
2024           1  0  0  0  0
cloud          0  0  0  0  1
course         1  0  0  0  1
date           0  0  1  0  0
github         0  1  0  0  0
google         0  0  0  0  1
homeworks      0  0  1  0  0
jan            1  0  0  0  0
listed         0  1  0  0  0
participation  0  0  0  1  0
prerequisites  0  1  0  0  0
python         0  0  0  0  1
registration   0  0  0  1  0
required       0  0  0  1  0
setup          0  0  0  0  1
start          0  0  1  0  0
starts         1  0  0  0  0
submit         0  0  1  0  0

In [26]:
from sklearn.feature_extraction.text import TfidfVectorizer

cv = TfidfVectorizer(stop_words='english')
X = cv.fit_transform(docs_example)

names = cv.get_feature_names_out()

df_docs = pd.DataFrame(X.toarray(), columns=names)
df_docs.round(2)

15th  2024  cloud  course  date  github  google  homeworks   jan  listed  \
0  0.46  0.46   0.00    0.37   0.0    0.00    0.00        0.0  0.46    0.00   
1  0.00  0.00   0.00    0.00   0.0    0.58    0.00        0.0  0.00    0.58   
2  0.00  0.00   0.00    0.00   0.5    0.00    0.00        0.5  0.00    0.00   
3  0.00  0.00   0.00    0.00   0.0    0.00    0.00        0.0  0.00    0.00   
4  0.00  0.00   0.46    0.37   0.0    0.00    0.46        0.0  0.00    0.00   

   participation  prerequisites  python  registration  required  setup  start  \
0           0.00           0.00    0.00          0.00      0.00   0.00    0.0   
1           0.00           0.58    0.00          0.00      0.00   0.00    0.0   
2           0.00           0.00    0.00          0.00      0.00   0.00    0.5   
3           0.58           0.00    0.00          0.58      0.58   0.00    0.0   
4           0.00           0.00    0.46          0.00      0.00   0.46    0.0   

   starts  submit  
0    0.46     0.0  
1    0.00     0.0  
2    0.00     0.5  
3    0.00     0.0  
4    0.00     0.0

In [27]:
query = "Do I need to know python to sign up for the January course?"

q = cv.transform([query])
q.toarray()

array([[0.        , 0.        , 0.        , 0.62791376, 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.77828292, 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        ]])

In [28]:
query_dict = dict(zip(names, q.toarray()[0]))
query_dict

doc_dict = dict(zip(names, X.toarray()[1]))
doc_dict

{'15th': np.float64(0.0),
 '2024': np.float64(0.0),
 'cloud': np.float64(0.0),
 'course': np.float64(0.0),
 'date': np.float64(0.0),
 'github': np.float64(0.5773502691896258),
 'google': np.float64(0.0),
 'homeworks': np.float64(0.0),
 'jan': np.float64(0.0),
 'listed': np.float64(0.5773502691896258),
 'participation': np.float64(0.0),
 'prerequisites': np.float64(0.5773502691896258),
 'python': np.float64(0.0),
 'registration': np.float64(0.0),
 'required': np.float64(0.0),
 'setup': np.float64(0.0),
 'start': np.float64(0.0),
 'starts': np.float64(0.0),
 'submit': np.float64(0.0)}

In [29]:
df_qd = pd.DataFrame([query_dict, doc_dict], index=['query', 'doc']).T

(df_qd['query'] * df_qd['doc']).sum()

np.float64(0.0)

In [30]:
X.dot(q.T).toarray()

array([[0.23490553],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.59579005]])

In [36]:
from sklearn.metrics.pairwise import cosine_similarity
score = cosine_similarity(X, q).flatten()

In [37]:
score

array([0.23490553, 0.        , 0.        , 0.        , 0.59579005])

In [39]:
import numpy as np


In [40]:
np.argsort(score)

array([1, 2, 3, 0, 4])

In [46]:
fields=['section','question','text']
matrices ={}
vectorizers ={}

In [47]:
for f in fields:
    cv =TfidfVectorizer(stop_words='english',min_df=3)
    X= cv.fit_transform(df[f])
    matrices[f] = X
    vectorizers[f] = cv

In [ ]:
df

In [48]:
matrices

{'section': <Compressed Sparse Row sparse matrix of dtype 'float64'
 	with 3094 stored elements and shape (948, 67)>,
 'question': <Compressed Sparse Row sparse matrix of dtype 'float64'
 	with 4333 stored elements and shape (948, 562)>,
 'text': <Compressed Sparse Row sparse matrix of dtype 'float64'
 	with 26463 stored elements and shape (948, 2118)>}

In [50]:
vectorizers

{'section': TfidfVectorizer(min_df=3, stop_words='english'),
 'question': TfidfVectorizer(min_df=3, stop_words='english'),
 'text': TfidfVectorizer(min_df=3, stop_words='english')}

In [52]:
n = len(df)
n

948

In [76]:
score = np.zeros(n)
query = "I just discovered the course, is it too late to join?"

boosts = {
    'question': 3     # question is 3times more importance than other
}

for f in fields:
    q = vectorizers[f].transform([query])
    X = matrices[f]

    f_score = cosine_similarity(X,q).flatten()
    boost = boosts.get(f,1.0)

    score = score + boost * f_score

In [77]:
filters ={ 
    'course':'data-engineering-zoomcamp'
}

In [78]:
for field, value in filters.items():
    mask = (df[field] ==value).astype(int)
    score = score * mask

In [79]:
idx = np.argsort(score)[-10:]

In [80]:
df.iloc[idx]

course                           section  \
10  data-engineering-zoomcamp  General course-related questions   
8   data-engineering-zoomcamp  General course-related questions   
2   data-engineering-zoomcamp  General course-related questions   
7   data-engineering-zoomcamp  General course-related questions   
0   data-engineering-zoomcamp  General course-related questions   
1   data-engineering-zoomcamp  General course-related questions   
34  data-engineering-zoomcamp  General course-related questions   
9   data-engineering-zoomcamp  General course-related questions   
4   data-engineering-zoomcamp  General course-related questions   
5   data-engineering-zoomcamp  General course-related questions   

                                             question  \
10  Course - ​​How many hours per week am I expect...   
8   Course - Can I get support if I take the cours...   
2   Course - Can I still join the course after the...   
7   Course - Can I follow the course after it fini...   
0                Course - When will the course start?   
1   Course - What are the prerequisites for this c...   
34               How can we contribute to the course?   
9   Course - Which playlist on YouTube should I re...   
4    Course - What can I do before the course starts?   
5              Course - how many Zoomcamps in a year?   

                                                 text  
10  It depends on your background and previous exp...  
8   Yes, the slack channel remains open and you ca...  
2   Yes, even if you don't register, you're still ...  
7   Yes, we will keep all the materials after the ...  
0   The purpose of this document is to capture fre...  
1   GitHub - DataTalksClub data-engineering-zoomca...  
34  Star the repo! Share it with friends if you fi...  
9   All the main videos are stored in the Main “DA...  
4   You can start by installing and setting up all...  
5   There are 3 Zoom Camps in a year, as of 2024. ...

In [81]:
class TextSearch:

    def __init__(self, text_fields):
        self.text_fields = text_fields
        self.matrices = {}
        self.vectorizers = {}

    def fit(self, records, vectorizer_params={}):
        self.df = pd.DataFrame(records)

        for f in self.text_fields:
            cv = TfidfVectorizer(**vectorizer_params)
            X = cv.fit_transform(self.df[f])
            self.matrices[f] = X
            self.vectorizers[f] = cv

    def search(self, query, n_results=10, boost={}, filters={}):
        score = np.zeros(len(self.df))

        for f in self.text_fields:
            b = boost.get(f, 1.0)
            q = self.vectorizers[f].transform([query])
            s = cosine_similarity(self.matrices[f], q).flatten()
            score = score + b * s

        for field, value in filters.items():
            mask = (self.df[field] == value).values
            score = score * mask

        idx = np.argsort(-score)[:n_results]
        results = self.df.iloc[idx]
        return results.to_dict(orient='records')

In [82]:
index = TextSearch(
    text_fields=['section', 'question', 'text']
)
index.fit(documents)

index.search(
    query='I just signed up. Is it too late to join the course?',
    n_results=5,
    boost={'question': 3.0},
    filters={'course': 'data-engineering-zoomcamp'}
)

[{'text': "Yes, even if you don't register, you're still eligible to submit the homeworks.\nBe aware, however, that there will be deadlines for turning in the final projects. So don't leave everything for the last minute.",
  'section': 'General course-related questions',
  'question': 'Course - Can I still join the course after the start date?',
  'course': 'data-engineering-zoomcamp'},
 {'text': "The purpose of this document is to capture frequently asked technical questions\nThe exact day and hour of the course will be 15th Jan 2024 at 17h00. The course will start with the first  “Office Hours'' live.1\nSubscribe to course public Google Calendar (it works from Desktop only).\nRegister before the course starts using this link.\nJoin the course Telegram channel with announcements.\nDon’t forget to register in DataTalks.Club's Slack and join the channel.",
  'section': 'General course-related questions',
  'question': 'Course - When will the course start?',
  'course': 'data-engineerin

In [88]:
X


<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 26463 stored elements and shape (948, 2118)>

In [93]:
from sklearn.decomposition import TruncatedSVD

X = matrices['text']
cv = vectorizers['text']

svd = TruncatedSVD(n_components=16)
X_emb = svd.fit_transform(X)

X_emb[0]

array([ 0.08800249, -0.07509245, -0.10016324,  0.05029961,  0.05104611,
        0.06149848,  0.01817686,  0.03585753, -0.18992964,  0.33489175,
        0.01839162,  0.10413448, -0.11075332, -0.07045928,  0.06894114,
       -0.00583701])

In [94]:
X_emb.shape

(948, 16)

In [96]:
query = 'I just signed up. Is it too late to join the course?'

Q = cv.transform([query])
Q_emb = svd.transform(Q)
Q_emb[0]

array([ 0.04353709, -0.03069741, -0.04395118,  0.01191654,  0.02593293,
        0.05317703,  0.00912235,  0.02237279, -0.11430408,  0.18088905,
        0.02295303,  0.07848131, -0.05841468, -0.02484091,  0.06143665,
        0.00233339])

In [97]:
np.dot(X_emb[0],Q_emb[0])

np.float64(0.1200248583322195)

In [99]:
score = cosine_similarity(X_emb, Q_emb).flatten()
idx = np.argsort(-score)[:10]
# list(df.loc[idx].text)
df.loc[idx]

course                           section  \
764  machine-learning-zoomcamp   Projects (Midterm and Capstone)   
449  machine-learning-zoomcamp  General course-related questions   
11   data-engineering-zoomcamp  General course-related questions   
7    data-engineering-zoomcamp  General course-related questions   
0    data-engineering-zoomcamp  General course-related questions   
450  machine-learning-zoomcamp  General course-related questions   
436  machine-learning-zoomcamp  General course-related questions   
440  machine-learning-zoomcamp  General course-related questions   
15   data-engineering-zoomcamp  General course-related questions   
814             mlops-zoomcamp        +-General course questions   

                                              question  \
764  What If I submitted only two projects and fail...   
449  The course has already started. Can I still jo...   
11   Certificate - Can I follow the course in a sel...   
7    Course - Can I follow the course after it fini...   
0                 Course - When will the course start?   
450                When does the next iteration start?   
436                      Is it going to be live? When?   
440  I filled the form, but haven't received a conf...   
15   Homework - Are late submissions of homework al...   
814  What if my answer is not exactly the same as t...   

                                                  text  
764  If you have submitted two projects (and peer-r...  
449  Yes, you can. You won’t be able to submit some...  
11   No, you can only get a certificate if you fini...  
7    Yes, we will keep all the materials after the ...  
0    The purpose of this document is to capture fre...  
450  The course is available in the self-paced mode...  
436  The course videos are pre-recorded, you can st...  
440  The process is automated now, so you should re...  
15   No, late submissions are not allowed. But if t...  
814  Please choose the closest one to your answer. ...

In [100]:
from sklearn.decomposition import NMF
nmf = NMF(n_components=16)
X_emb = nmf.fit_transform(X)
X_emb[0]

array([0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.31051113,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        ])

In [101]:
Q = cv.transform([query])
Q_emb = nmf.transform(Q)
Q_emb[0]

array([0.        , 0.00114757, 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.17352199,
       0.        , 0.        , 0.        , 0.        , 0.00063408,
       0.        ])

In [104]:
score = cosine_similarity(X_emb, Q_emb).flatten()
idx = np.argsort(-score)[:10]
# list(df.loc[idx].text)
df.loc[idx]

course                           section  \
0    data-engineering-zoomcamp  General course-related questions   
451  machine-learning-zoomcamp  General course-related questions   
449  machine-learning-zoomcamp  General course-related questions   
814             mlops-zoomcamp        +-General course questions   
2    data-engineering-zoomcamp  General course-related questions   
764  machine-learning-zoomcamp   Projects (Midterm and Capstone)   
436  machine-learning-zoomcamp  General course-related questions   
437  machine-learning-zoomcamp  General course-related questions   
11   data-engineering-zoomcamp  General course-related questions   
7    data-engineering-zoomcamp  General course-related questions   

                                              question  \
0                 Course - When will the course start?   
451      Can I submit the homework after the due date?   
449  The course has already started. Can I still jo...   
814  What if my answer is not exactly the same as t...   
2    Course - Can I still join the course after the...   
764  What If I submitted only two projects and fail...   
436                      Is it going to be live? When?   
437                          What if I miss a session?   
11   Certificate - Can I follow the course in a sel...   
7    Course - Can I follow the course after it fini...   

                                                  text  
0    The purpose of this document is to capture fre...  
451  No, it’s not possible. The form is closed afte...  
449  Yes, you can. You won’t be able to submit some...  
814  Please choose the closest one to your answer. ...  
2    Yes, even if you don't register, you're still ...  
764  If you have submitted two projects (and peer-r...  
436  The course videos are pre-recorded, you can st...  
437  Everything is recorded, so you won’t miss anyt...  
11   No, you can only get a certificate if you fini...  
7    Yes, we will keep all the materials after the ...

In [3]:
import torch
from transformers import BertModel, BertTokenizer

tokenizer = BertTokenizer.from_pretrained("bert-base-uncased")
model = BertModel.from_pretrained("bert-base-uncased")
model.eval()  # Set the model to evaluation mode if not training

tokenizer_config.json:   0%|          | 0.00/48.0 [00:00<?, ?B/s]

d:\anaconda\Lib\site-packages\huggingface_hub\file_download.py:143: UserWarning: `huggingface_hub` cache-system uses symlinks by default to efficiently store duplicated files but your machine does not support them in C:\Users\ASUS\.cache\huggingface\hub\models--bert-base-uncased. Caching files will still work but in a degraded version that might require more space on your disk. This warning can be disabled by setting the `HF_HUB_DISABLE_SYMLINKS_WARNING` environment variable. For more details, see https://huggingface.co/docs/huggingface_hub/how-to-cache#limitations.
To support symlinks on Windows, you either need to activate Developer Mode or to run Python as an administrator. In order to activate developer mode, see this article: https://docs.microsoft.com/en-us/windows/apps/get-started/enable-your-device-for-development
  warnings.warn(message)


vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/466k [00:00<?, ?B/s]

config.json:   0%|          | 0.00/570 [00:00<?, ?B/s]

Xet Storage is enabled for this repo, but the 'hf_xet' package is not installed. Falling back to regular HTTP download. For better performance, install the package with: `pip install huggingface_hub[hf_xet]` or `pip install hf_xet`


model.safetensors:   0%|          | 0.00/440M [00:00<?, ?B/s]

BertModel(
  (embeddings): BertEmbeddings(
    (word_embeddings): Embedding(30522, 768, padding_idx=0)
    (position_embeddings): Embedding(512, 768)
    (token_type_embeddings): Embedding(2, 768)
    (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
    (dropout): Dropout(p=0.1, inplace=False)
  )
  (encoder): BertEncoder(
    (layer): ModuleList(
      (0-11): 12 x BertLayer(
        (attention): BertAttention(
          (self): BertSdpaSelfAttention(
            (query): Linear(in_features=768, out_features=768, bias=True)
            (key): Linear(in_features=768, out_features=768, bias=True)
            (value): Linear(in_features=768, out_features=768, bias=True)
            (dropout): Dropout(p=0.1, inplace=False)
          )
          (output): BertSelfOutput(
            (dense): Linear(in_features=768, out_features=768, bias=True)
            (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
            (dropout): Dropout(p=0.1, inplace=False

In [4]:
texts = [
    "Yes, we will keep all the materials after the course finishes.",
    "You can follow the course at your own pace after it finishes"
]
encoded_input = tokenizer(texts, padding=True, truncation=True, return_tensors='pt')

In [5]:
with torch.no_grad():  # Disable gradient calculation for inference
    outputs = model(**encoded_input)
    hidden_states = outputs.last_hidden_state

In [6]:
sentence_embeddings = hidden_states.mean(dim=1)
sentence_embeddings.shape

torch.Size([2, 768])

In [7]:
sentence_embeddings

tensor([[ 0.3600, -0.1607,  0.3545,  ...,  0.0429,  0.0348, -0.0382],
        [ 0.1785, -0.5000,  0.2528,  ..., -0.1141, -0.3361,  0.4110]])

In [8]:
X_emb = sentence_embeddings.numpy()